matrix:
  include:
      - os: linux
        dist: xenial
        sudo: required
        language: python
        python: 3.7
        node_js: 10

addons:
  chrome: stable

services:
  - redis-server
  - xvfb

git:
  depth: 3

install:
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - wget http://mirror.jkanetwork.com/Datasets/data.sqlite -O ./ubumlaas/data.sqlite
  - wget http://mirror.jkanetwork.com/Datasets/ubumlaas.tar -O /tmp/ubumlaas.tar
  - mkdir -p $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas
  - tar -xvf /tmp/ubumlaas.tar -C $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas
  - npm install -g chromedriver

before_script:
  - wget http://mirror.jkanetwork.com/Datasets/env_variables.sh -O env_variables.sh
  - source env_variables.sh
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3
  - python app.py > /dev/null 2> /dev/null &
  - sleep 20

script:
  - python tests.py
  - python -m pytest -p no:warning test/test_selenium.py
