matrix:
  include:
      - os: linux
        dist: trusty
        sudo: required
        language: python
        python: 3.6

git:
  depth: 3

before_install:
  - sudo apt update
  - sudo apt install -y redis-server
  - sudo service redis-server start

install:
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - wget http://mirror.jkanetwork.com/Datasets/data.sqlite -O ./ubumlaas/data.sqlite
  - wget http://mirror.jkanetwork.com/Datasets/ubumlaas.tar -O /tmp/ubumlaas.tar
  - mkdir -p $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas
  - tar -xvf /tmp/ubumlaas.tar -C $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas

before_script:
  - wget http://mirror.jkanetwork.com/Datasets/env_variables.sh -O env_variables.sh
  - bash env_variables.sh

script:
  - python tests.py