os: linux
dist: bionic
language: python
python: 3.7
node_js: 10
jdk:
  - openjkd8
jobs:
  include:
      - os: linux
        dist: xenial
        language: python
        python: 3.7
        node_js: 10
        jdk:
          - openjkd8

git:
  depth: 3

addons:
  firefox: "49.0"
  apt:
    packages:
      - chromium-chromedriver

services:
  - redis
  - xvfb

install:
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - wget https://github.com/dpr1005/UBUMLaaS/raw/CICD/test/utils/testDB.sqlite -O $TRAVIS_BUILD_DIR/ubumlaas/data.sqlite --no-check-certificate
  - wget https://github.com/dpr1005/UBUMLaaS/raw/CICD/test/utils/ubumlaas.tar -O /tmp/ubumlaas.tar --no-check-certificate
  - mkdir -p $TRAVIS_BUILD_DIR/ubumlaas/datasets/{ubumlaas,ubumlaas2}
  - mkdir -p $TRAVIS_BUILD_DIR/test/datasets
  - tar -xvf /tmp/ubumlaas.tar -C $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas
  - cp $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas/* $TRAVIS_BUILD_DIR/test/datasets
  - cp $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas/* $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas2
  
before_script:
  - wget https://raw.githubusercontent.com/dpr1005/UBUMLaaS/CICD/test/utils/env_variables -O env_variables.sh --no-check-certificate
  - source env_variables.sh
  - python migrate.py
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3
  - python app.py &
  - sleep 20  

script:
  - python -m pytest test/test_selenium.py --verbose
  - python -m test.tests
