matrix:
  include:
      - os: linux
        dist: trusty
        sudo: required
        language: python
        python: 3.6

git:
  depth: 3

before_install:
  - sudo apt update
  - sudo apt install -y redis-server
  - sudo service redis-server start
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

before_script:
  - conda create -n UBUMLaaS python=3.6
  - conda activate UBUMLaaS
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - wget http://mirror.jkanetwork.com/Datasets/data.sqlite -O ./ubumlaas/data.sqlite
  - wget http://mirror.jkanetwork.com/Datasets/ubumlaas.tar -O /tmp/ubumlaas.tar
  - mkdir -p $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas
  - tar -xvf /tmp/ubumlaas.tar $TRAVIS_BUILD_DIR/ubumlaas/datasets/ubumlaas
  - wget http://mirror.jkanetwork.com/Datasets/env_variables.sh -O env_variables.sh
  - bash env_variables.sh

